### ISSUE TITLE
Update to work with Hashie 2.0

### ISSUE THREAD

**Issue by sferik** [tcocca/rash#8] opened 2013-02-25 20:34 UTC
Currently, `rash` specifies a dependency on `hashie` ~> 1.2.0. I tried updating this dependency to allow version 2.0 but this resulted in a test failure: https://gist.github.com/317cde6786318bcb5041

Could you please look into why this is happening and release a new version of `rash` that is compatible with the latest version of `hashie`?

Thanks!

**Comment by tcocca** [comment] 2013-02-25 20:47
Thanks @sferik Looks like something changed here.  When you used to merge in a Mash into a rash it would convert the keys of the Mash, now its not doing that. At least not when calling update and passing a Mash.  Let me see whats going on here.  Hopefully it'll be something easy.

**Comment by tcocca** [comment] 2013-02-25 21:26
@sferik I think I tracked this down to the following commit  https://github.com/intridea/hashie/commit/3fa612626a6034d140b84b2a474fa7e27af64293

@jch If I am reading this commit correct, Mash used to convert hashes or dashes or anything to a Mash when you assigned that new object to a value in the mash, or did an #update or #merge witch a plain hash (or other subclass) it would convert it to a mash when it assigned or merged.  What was the reasoning behind this change?

If that is the case how do you think we should handle it in rash?  I am inclined to say that if you are merging stuff into a rash or assigning new hashes to the value of a rash it should convert that new hash to rash, not leave it as the current type?

Thoughts?

Thanks,
~ Tom

**Comment by tcocca** [comment] 2013-02-27 12:06
@sferik ping.  Any thoughts here?

**Comment by sferik** [comment] 2013-02-27 18:45
I think it’s an interesting question…

Should you be able to embed another hash inside a `Hashie::Rash` or should the hash be converted to a `Hashie::Rash` on assignment or `#merge`? I don’t know. I could see someone being surprised if their object got converted. On the other hand, it should be easy to create a nested `Hashie::Rash`.

I’d be curious to what @jch has to say, since he was the one who made this change. Was this an intended consequence of https://github.com/intridea/hashie/commit/3fa612626a6034d140b84b2a474fa7e27af64293?

I know it’s already been [debated and decided](https://github.com/intridea/hashie/issues/7) but I think this is actually an argument for merging `Hashie::Rash` into the `hashie` repo. If [this test](https://gist.github.com/sferik/317cde6786318bcb5041) was part of that project, the consequences of this change would have been noticed much earlier and could have been resolved before `hashie` 2.0 shipped.

**Comment by tcocca** [comment] 2013-02-27 19:05
@sferik the fix to maintain the old functionality of converting the new hash (or hash based object) to a new rash is actually kind of simple  -  https://github.com/tcocca/rash/compare/hashie2

The question becomes whether this is intended behavior on merge/update/assignment to convert the object to a rash.

Part of me thinks you are using rash because you want a rash, so if you have a rash and you merge something in, why not get a rash in return?  

Also, if you look at the specs I just added here: https://github.com/tcocca/rash/commit/8b5789f6e9977b83243ebdb70917b713e61544ce  you can see that regular hash key access still works, so I guess why not do the conversion if you can still use regular hash access?

But I agree, I'd like to hear the argument from @jch for this change.

**Comment by sferik** [comment] 2013-02-27 19:09
There’s a [long-term plan](https://twitter.com/mbleigh/status/302874448711786496) to make `hashie` more modular, such that each subclass is built-up from its component parts. For example, you’d implement `Hashie::Mash` simply by mixing in the `Hashie::Extensions::IndifferentAccess` module, the `Hashie::Extensions::MethodAccess` module, etc. until it had all the behaviors you wanted in a `Mash`. The actually `Mash` class would contain no imperative code, just a handful of declarative `include` statements. If that’s how `hashie` 3.0 worked, it would be much easier to define new hash-like objects and extend the behavior of existing ones in predictable ways.

IMHO, this is the goal we should all be working toward.

**Comment by tcocca** [comment] 2013-02-27 19:16
That sounds like a nice plan for the Hashie.  Rash would no longer inherit from Mash at that point probably, it would just include the same modules I guess.

In the mean time however, hashie 2.0 is out so what are you leaning towards on the issue. To rash or not to rash, that is the question.

**Comment by sferik** [comment] 2013-02-27 19:19
I think you should probably merge your [hashie2 branch](https://github.com/tcocca/rash/compare/hashie2) to master to preserve compatibility with previous version of `rash`.

**Comment by sferik** [comment] 2013-02-27 19:24
This almost certainly isn’t the right place for this comment, but while it’s on my mind, I also think `Hashie::Mash` ought to raise an error when you try assigning or merging a key that conflicts with an existing `Hash` method name. For example:

``` ruby
mash = Hashie::Mash.new
mash.clear = "abc"
Hashie::KeyError: conflict with `Hash#clear`
```

In my opinion, the biggest problem with `hashie` is that it’s far too easy to shoot yourself in the foot by accidentally assigning or merging a key that conflicts with an existing `Hash` method name.

**Comment by tcocca** [comment] 2013-02-27 19:24
perfect, I'll get that done and release a 0.4.0 version shortly

**Comment by tcocca** [comment] 2013-02-27 19:32
v0.4.0 for hashie2 is out: https://rubygems.org/gems/rash/versions/0.4.0

Thanks @sferik

**Closed as completed by tcocca** 2013-02-27 19:32 UTC

**Comment by jch** [comment] 2013-02-27 19:53
Coming in to the discussion a bit late. @tcocca thanks for the new cut of rash!

The reasoning behind the change was I wanted subclasses of Mash to be nested by default. Without the change, nested instances of the subclass wouldn't keep the same custom behavior.

I agree with @sferik for pulling out all the functionality of a mash into modules for 3.x, but I'm not sure when we'll get around to that. With that in mind, I'd rather get rash merged in now and give @tcocca commit access. He can then refactor rash to include a bunch of modules for 3.x.  Thoughts @mbleigh?
